### ISSUE TITLE
No build:css defined in package.json

### ISSUE THREAD

**Issue by seanmcmills** [matrix-org/react-dnd-sorting-example#1]
if i am not mistaken, no build:css defined in package.json. thank you very much for this repo.

`npm run build:css
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:css"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.3

npm ERR! missing script: build:css
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/seanmcmills/repos/react-dnd-sorting-example/npm-debug.log`

---

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:css' ]
2 info using npm@3.10.3
3 info using node@v4.4.5
4 verbose stack Error: missing script: build:css
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /Users/xxxxx/repos/react-dnd-sorting-example
6 error Darwin 15.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:css"
8 error node v4.4.5
9 error npm  v3.10.3
10 error missing script: build:css
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
`

**Comment by ara4n** [comment]
i'd totally forgotten I ever wrote this :S

The reason there's no build:css is that the example is so trivial that i don't think there is any custom
CSS involved.

These days I would strongly recommend using ES6 rather than ES5, plus react 0.13 is very obsolete. This project should just be used as an illustration of how react-dnd's API works in "plain" ES5 and nothing more.
